name: Validate Dataset Entries

on: 
  push:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install ajv-cli
        run: npm install -g ajv-cli

      - name: Validate JSON entries
        run: |
          for file in entries/*.json; do
            echo "Validating $file"
            ajv validate -s schemas/entry.schema.json -d "$file" --strict=false || exit 1
          done

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.12'

      - name: Install Python dependencies
        run: pip install sympy==1.12.0

      - name: Run programmatic verifications
        run: python scripts/verify_programmatic.py

      - name: Generate index
        run: npm run build

      - name: Check for index changes
        id: verify-changed-files
        run: |
          if git diff --quiet docs/entries_index.html; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit updated index
        if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'push'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/entries_index.html
          git commit -m "Auto-update entries index [skip ci]"
          git push
