name: Validate Dataset Entries

on: 
  push:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.12'

      - name: Install Python dependencies
        run: pip install sympy==1.12.0 jsonschema

      - name: Validate JSON entries
        run: |
          for file in entries/*.json; do
            echo "Validating $file"
            python scripts/validate_schema.py "$file" || exit 1
          done

      - name: Run programmatic verifications
        run: python scripts/verify_programmatic.py

      - name: Generate index
        run: python scripts/generate_index.py

      - name: Generate notebooks
        run: python scripts/generate_notebooks.py

      - name: Check for changes
        id: verify-changed-files
        run: |
          if git diff --quiet docs/entries_index.html notebooks/; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit updated files
        if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'push'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/entries_index.html notebooks/
          git commit -m "Auto-update entries index and notebooks [skip ci]"
          git push
